#!/bin/bash

service nginx stop
apt-get update
apt-get install nginx -y
sed -i 's/user\s*nginx;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default
service nginx restart
ps aux | grep nginx
nc -z 0 8080

